# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_manager/account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61\x63\x63ount_manager/account.proto\x12\x07\x61\x63\x63ount\x1a\x1bgoogle/protobuf/empty.proto\"\xb7\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x12\n\nfirst_name\x18\x04 \x01(\t\x12\x11\n\tlast_name\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\x11\n\tis_active\x18\x07 \x01(\x08\x12\x10\n\x08is_staff\x18\x08 \x01(\x08\x12\x14\n\x0cis_superuser\x18\t \x01(\x08\x12\x0e\n\x06groups\x18\n \x03(\x05\"\x11\n\x0fUserListRequest\"!\n\x13UserRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"T\n\x12UserCreateResponse\x12!\n\x05token\x18\x01 \x01(\x0b\x32\x12.account.UserToken\x12\x1b\n\x04user\x18\x02 \x01(\x0b\x32\r.account.User\"6\n\x10UserLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1a\n\tUserToken\x12\r\n\x05token\x18\x01 \x01(\t2\xb3\x02\n\x0bUserManager\x12\x31\n\x04List\x12\x18.account.UserListRequest\x1a\r.account.User0\x01\x12&\n\x06\x43reate\x12\r.account.User\x1a\r.account.User\x12\x37\n\x08Retrieve\x12\x1c.account.UserRetrieveRequest\x1a\r.account.User\x12&\n\x06Update\x12\r.account.User\x1a\r.account.User\x12\x30\n\x07\x44\x65stroy\x12\r.account.User\x1a\x16.google.protobuf.Empty\x12\x36\n\x05Login\x12\x19.account.UserLoginRequest\x1a\x12.account.UserTokenb\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_USERLISTREQUEST = DESCRIPTOR.message_types_by_name['UserListRequest']
_USERRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['UserRetrieveRequest']
_USERCREATERESPONSE = DESCRIPTOR.message_types_by_name['UserCreateResponse']
_USERLOGINREQUEST = DESCRIPTOR.message_types_by_name['UserLoginRequest']
_USERTOKEN = DESCRIPTOR.message_types_by_name['UserToken']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'account_manager.account_pb2'
  # @@protoc_insertion_point(class_scope:account.User)
  })
_sym_db.RegisterMessage(User)

UserListRequest = _reflection.GeneratedProtocolMessageType('UserListRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERLISTREQUEST,
  '__module__' : 'account_manager.account_pb2'
  # @@protoc_insertion_point(class_scope:account.UserListRequest)
  })
_sym_db.RegisterMessage(UserListRequest)

UserRetrieveRequest = _reflection.GeneratedProtocolMessageType('UserRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERRETRIEVEREQUEST,
  '__module__' : 'account_manager.account_pb2'
  # @@protoc_insertion_point(class_scope:account.UserRetrieveRequest)
  })
_sym_db.RegisterMessage(UserRetrieveRequest)

UserCreateResponse = _reflection.GeneratedProtocolMessageType('UserCreateResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERCREATERESPONSE,
  '__module__' : 'account_manager.account_pb2'
  # @@protoc_insertion_point(class_scope:account.UserCreateResponse)
  })
_sym_db.RegisterMessage(UserCreateResponse)

UserLoginRequest = _reflection.GeneratedProtocolMessageType('UserLoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERLOGINREQUEST,
  '__module__' : 'account_manager.account_pb2'
  # @@protoc_insertion_point(class_scope:account.UserLoginRequest)
  })
_sym_db.RegisterMessage(UserLoginRequest)

UserToken = _reflection.GeneratedProtocolMessageType('UserToken', (_message.Message,), {
  'DESCRIPTOR' : _USERTOKEN,
  '__module__' : 'account_manager.account_pb2'
  # @@protoc_insertion_point(class_scope:account.UserToken)
  })
_sym_db.RegisterMessage(UserToken)

_USERMANAGER = DESCRIPTOR.services_by_name['UserManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=72
  _USER._serialized_end=255
  _USERLISTREQUEST._serialized_start=257
  _USERLISTREQUEST._serialized_end=274
  _USERRETRIEVEREQUEST._serialized_start=276
  _USERRETRIEVEREQUEST._serialized_end=309
  _USERCREATERESPONSE._serialized_start=311
  _USERCREATERESPONSE._serialized_end=395
  _USERLOGINREQUEST._serialized_start=397
  _USERLOGINREQUEST._serialized_end=451
  _USERTOKEN._serialized_start=453
  _USERTOKEN._serialized_end=479
  _USERMANAGER._serialized_start=482
  _USERMANAGER._serialized_end=789
# @@protoc_insertion_point(module_scope)
